site_name: DCApy
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Code Reference:
    - dca: dca-reference.md
    - filters: filters-reference.md
    - models: models-reference.md 
    - weiner: wiener-reference.md 
  - Tutorial:
    - Intro: tutorial/1-Intro.md
    - Arps Declination:
      - Arps Basics: tutorial/1a-Tutorial-Arps_basic_dca.md
      - Arps Class: tutorial/1b-Tutorial-Arps_Class/1b-Tutorial-Arps_Class.md
      - Wor Basis&Class: tutorial/1c-Tutorial-Wor_basic.md


repo_url: https://github.com/orkahub/dcapy
repo_name: orkahub/dcapy

plugins:
  - search
  - mkdocstrings
