site_name: DCApy
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  #- Code Reference:
    #- dca: dca-reference.md
    #- filters: filters-reference.md
    #- cashflow: schedule-reference.md 
    #- cashflow: cashflow-reference.md 
    #- weiner: wiener-reference.md 
  - Tutorial:
    - Intro: examples/1-Intro.md
    - Arps Declination:
      - Arps Basics: examples/1-basics/1a-Tutorial-Arps_basic_dca.ipynb
      - Arps Class: examples/1-basics/1b-Tutorial-Arps_Class.ipynb
      - Wor Basis&Class: examples/1-basics/1c-Tutorial-Wor_basic.ipynb
      - Probabilistic Class: examples/1-basics/1d-Tutorial_Probabilistic_Variables.ipynb
      - Data Fitting Aprs and Wor: examples/1-basics/1e-Tutorial_Fit data.ipynb
    - Cashflows:
      - Cashflow Basics: examples/2-cashflow/2a-Cashflow Basics.ipynb
    - Wiener Proccesses:
      - Wiener Proccesses: examples/3-Wiener/3-Wiener_procces.ipynb
    - Forecast Scheduling:
      - Introduction: examples/4-schedules/4a-Tutorial_Scheduling_intro.ipynb
      - Period Class : examples/4-schedules/4b-Tutorial_Period.ipynb
      - Scenario Class : examples/4-schedules/4c-Tutorial_Scenario.ipynb
      - Wells Class : examples/4-schedules/4d-Tutorial_Wells.ipynb
      - WellsGroup Class : examples/4-schedules/4e-Tutorial_WellsGroup_yml.ipynb
    - Cloud API:
      - Introduction: examples/5-CloudAPI/5a-CloudAPI.ipynb
  - Release Notes: release_notes.md

repo_url: https://github.com/scuervo91/dcapy
repo_name: scuervo91/dcapy

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - admonition
