site_name: DCApy
theme:
  name: material
  palette:
    scheme: preference
    primary: white
    accent: deep purple
nav:
  - Home: index.md
  - Code Reference:
    - dca: dca-reference.md

plugins:
  - search
  - mkdocstrings
