name: test-markdown
on: [push]

jobs:
  build:
    name: autopy-lot-md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: autopy-lot 
        uses: deep5050/autopy-lot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check: 'all'
          input_type: 'ipynb'
          comment_magics: 'true'
          split_at_heading: 'true'
          output_type: 'markdown'
          output_dir: './docs/tutorial_/'
